guru:
  jms:
    username: JMS Username
    password: somepass
    url: SomeUrl

---
spring:
  profiles: de
guru:
  jms:
    username: JMS Username $$$$$ German Inam override mishe montoha to yml document2